### ISSUE TITLE
Getting 0.0 or -infinity for all metrics

### ISSUE THREAD

**Issue by zandegran** [SimpleFinance/kafka-dropwizard-reporter#5]
Just running in single node, give all 0.0 or -infinity for some. I'm bombarding the node with 100,000 records per second. I also have a consumer. 

**For debugging:** I have added `System.printf("############  %70s : %s\n",name, kafkaMetric.value());` in the method metricsChange 
Using Kafka 2.12-0.11.0.0

**Some sample output**

############ org.apache.kafka.common.metrics.controller-channel-metrics.0.request-size-max : -Infinity

**Comment by jklukas** [comment]
I'm not expecting `controller-channel-metrics` for clients and I don't see that metric group documented in http://kafka.apache.org/documentation.html#monitoring

Here's an example path I'd expect to be available for a consumer: `org.apache.kafka.common.metrics.consumer-metrics.<client.id>.incoming-byte-rate`.

**Comment by zandegran** [comment]
This is all I get from a 10 minute session [https://pastebin.com/fNcqE0t8](https://pastebin.com/fNcqE0t8) from starting the broker to stopping it.

**Comment by jklukas** [comment]
It's still not clear to me what these metrics are, since I don't see these names in the Kafka docs. How have you installed the reporter? Can you give some more info about your setup?

It looks like these are broker metrics that you're showing. This project is a metrics reporter for clients rather than the broker. The expectation is that you'd configure this reporter in your client application's Kafka consumers. Are you somehow running this on the broker?

**Comment by zandegran** [comment]
Yes, Thanks and it makes total sense. I have attached this to the broker. via kafka settings properties file.  Looks like I should do it with either producer or consumer.

**Comment by jklukas** [comment]
Cool. I'm glad the broker/client piece is figured out. I'm actually surprised that it was possible to get this connected to the broker at all. But obviously, it did instantiate the reporter since it produced the printf messages.

I'll close this, but do let me know if you have success or difficulties integrating this to your producer or consumer.

**Comment by zandegran** [comment]
Hi, still no usable metrics. [https://pastebin.com/kfUp0aB0](https://pastebin.com/kfUp0aB0) I'm attaching it to consumer. I'm getting all Zeros. Should I do something else?

**Comment by jklukas** [comment]
On consumer startup, it will call `init`, which will call `metricChange` for each metric. At that time, the metrics are new, so it seems reasonable that they'd all report nonsense values.

I don't know the context of the application in which you're launching this consumer. In a Dropwizard application, you could hit the `/metrics` endpoint or configure the CSV reporter to periodically report out the current values of the metrics in the registry.

I expect these metrics will look more reasonable if you access values some time after initialization.

**Comment by zandegran** [comment]
Thank you. I see that `init ` is getting called. But nothing after that. I tried running overnight. 
**About Implementation:** It's not a dropwizard application. It's a very simple java program. [https://pastebin.com/dv7bk0ah](https://pastebin.com/dv7bk0ah)  All I want is to see the metrics printed. I'm generating constant traffic.

I don't understand what do you mean by  "configure the CSV reporter"

**Comment by jklukas** [comment]
All this kafka-dropwizard-reporter package is doing is registering each Kafka client metric as a Gauge in a Dropwizard Metrics registry.

In order to see the values of the metrics, you need to access the default Dropwizard Metrics registry and dump them out.

In a Dropwizard application, you'd have a yaml config where you could tell the app to [dump metrics to a CSV file](http://www.dropwizard.io/1.1.2/docs/manual/configuration.html#csv-reporter).

Outside a Dropwizard app, you probably need to do some more manual setup. The Dropwizard Metrics docs include some instructions about [instantiating a Reporter](http://metrics.dropwizard.io/3.2.3/manual/graphite.html). You can likely do something similar for the [CSV reporter](https://github.com/dropwizard/metrics/blob/3.2-development/metrics-core/src/main/java/com/codahale/metrics/CsvReporter.java).

**Comment by zandegran** [comment]
I understand that kafka-dropwizard-reporter package is just registering. That is why, I have a Print statement to output to stdio. Isn't it enough to see the values?

**Comment by jklukas** [comment]
> I have a Print statement to output to stdio

But this print statement is executing only during `init`, before any values have passed into the metrics. You'd need to make that print statement at some later time to see non-empty values.

Also, the print statement you have is accessing the Kafka metric value directly. So, even if that did print out a valid value, it doesn't prove that `kafka-dropwizard-reporter` is doing anything.

If you want to do this with print statements, you could access the Dropwizard metric registry in your main application code via `SharedMetricRegistries.getOrCreate("default")` and then have some loop to periodically loop through the registered gauges and print their values.

**Comment by zandegran** [comment]
Awesome! and thanks! This works.
`private static void printRegistry() throws IllegalArgumentException, IllegalAccessException {
       Map<String, Gauge> gauges = registry.getGauges();
       Iterator iter = gauges.entrySet().iterator();
       while (iter.hasNext()) {
    	   Entry entry = (Entry) iter.next();
    	   for (Field field: entry.getValue().getClass().getDeclaredFields()) {
    		   field.setAccessible(true);
			   //System.out.println(field.getName() + ": " + field.get(entry.getValue()).toString());
    		   if (field.getName().toString().endsWith("kafkaMetric")) {
    			   KafkaMetric k = (KafkaMetric) field.get(entry.getValue());
    			   System.out.printf("%70s : %s \n",sanitizeName(k.metricName()) ,k.value());
    		   }
    	   }
       }
       System.out.println("\n \n");
   }`

My Idea is to fetch these and update as zookeeper znodes periodically, so that information from all nodes would be accessible in one place. Do you think it's good Idea and would work?

**Comment by jklukas** [comment]
> My Idea is to fetch these and update as zookeeper znodes periodically, so that information from all nodes would be accessible in one place

I've never heard of using zookeeper to hold recent metrics values, but I see no reason why that wouldn't work. I'm used to folks sending metrics to a time-series database or metrics aggregation system like Graphite.

**Comment by zandegran** [comment]
Thanks for your input :)
